
bai5 = "1. Commit Message:\n"
bai5 += "   Ghi chú mô tả nội dung thay đổi khi commit.\n"
bai5 += "   Ví dụ: git commit -m \"Fix login bug\"\n"
bai5 += "2. Pull Request Comment:\n"
bai5 += "   Bình luận khi review mã trong Pull Request.\n"
bai5 += "   Gồm: bình luận chung, bình luận từng dòng, yêu cầu thay đổi.\n"
bai5 += "3. Issue Comment:\n"
bai5 += "   Ghi chú, thảo luận trong mục Issue (báo lỗi, đề xuất).\n"
bai5 += "   Có thể tag người và liên kết đến commit/PR khác.\n"
bai5 += "4. Tag Annotation:\n"
bai5 += "   Ghi chú khi tạo tag (phiên bản).\n"
bai5 += "   Ví dụ: git tag -a v1.0 -m \"First release\"\n"
bai5 += "5. Git Notes:\n"
bai5 += "   Ghi chú thêm cho commit mà không thay đổi nội dung commit.\n"
bai5 += "   Lệnh: git notes add -m \"Thông tin thêm\"\n"
bai5 += "6. README / Tài liệu:\n"
bai5 += "   Ghi chú trong file README.md, hướng dẫn sử dụng dự án."
print(bai5)